version: "3.2"
services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  basketservice:
    build: .
    ports:
      - "8085:80"
    restart: always
    depends_on:
      - redis
    environment:
      - WAIT_HOSTS=redis:6379

          
        

